### PR TITLE
Fix coins not consistently giving coins to users

### LINKED ISSUE #11: !coinsall does not always give users coins
The cause for this is unknown, I've had scenarios during testing where it works and scenarios where it hasn't both on development and production. Not sure how to replicate the issue. But the problem might potentially exist somewhere in the `twitchApi.js` file. I know that there are several API calls made in `!coinsall`.

### PR DESCRIPTION
**Pull request by syntag**
### Overview
Fixes issue where `!coinsall` command was not consistently giving coins to users.

#### Batching
Added `getUsersByUsernames` function to batch users in groups of 100 ([Twitch API Limit](https://dev.twitch.tv/docs/api/reference#get-users)) to send fewer requests in bulk. Previously, API was returning 429 (Too Many Requests) error causing the requests to be rejected.

### Notes
* Refactor `getViewers()` using `_.flatMapDeep()`
* Add error catching to `getUsersByUsernames`
* Add guards for user not found when giving/taking coins

### Related issues
[Fixes #11](https://github.com/DevWars/devwars-bot/issues/11)

### CODE REVIEW

File: src/apis/twitchApi.js [hunk 1]
```diff
@@ -7,40 +7,35 @@ const twitchUrl = 'https://api.twitch.tv/helix';
...
+        return _.uniq(chatters);
     } catch (error) {
         console.log('twitch.getViewers', error);
     }
 }
 
-async function getUserByUsername(username) {
-    const req = await axios.get(`${twitchUrl}/users?login=${username}`, {
-        headers: { 'Client-ID': process.env.TWITCH_CLIENT },
+async function getUsersByUsernames(usernames) {
```
Comment (stephen-slm) [inline src/apis/twitchApi.js:17]: You can make this a spread operator if helps with not having to pass around arrays? Just preference but not sure if you knew of it. 

```js
function a (...b) { console.log(b) }

a(1);
a(1, 2, 3, 4, 5);
a(...[1, 2, 3, 4, 5])
```

**Review by stephen-slm — APPROVED** [review]

**Comment by stephen-slm** [comment]
@SYNTAG might be worth using https://lodash.com/docs/#isNil over truthy checks since its more reliable in understanding that it was null or undefined cases and its using the lodash lib already?
